shell:
  id:
    value: "https://aausmartlab.com/Assets/Resource/MADE/ACOPOS6D/bf30b0a7-d2ba-41ab-989f-503e0b553ada"
  idShort:
    value: "ACOPOS6D"

submodels:
  Item_Capacity:
    Internal_Part_Storages:
      - Internal_Part_Storage_1:
          Storage_Size:
            value: 1
          Storing_Method:
            value: "First_In_First_Out"
          Storage_Type:
            value: "Output"
          Part_Types:
            - Part_Type_1:
                Part_Type_Id:
                  value: "https://aausmartlab.com/Assets/Product/Component/AAU/Bottom_Cover"
                Quantity:
                  value: 0

  Communication:
    Communication_Methods:
      - UNS_Communication:
          Broker_Address:
            value: "100.117.139.24"
          Protocol:
            value: "MQTT"
          Port:
            value: 1883
          Base_Topic:
            value: "AAU/FIB14/SmartLab/PL1/Stations"
          QoS:
            value: 2

  Location:
    General_Information:
      Building:
        value: FIB_14
      Production_Line:
        value: "Production_Line_1"

    Connection_Points:
      - ACOPOS6D_Connection_Point_1:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_1"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_2:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_2"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_3:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_3"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_4:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_4"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_5:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_5"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_6:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_6"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_7:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_7"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_8:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_8"
          Connection_Type:
            value: "In-Outfeed"
      - ACOPOS6D_Connection_Point_9:
          Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_9"
          Connection_Type:
            value: "In-Outfeed"

    Resource_Connections:
      - Resource_Connection_1:
          Own_Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_7"
          Connection_Resource_Id:
            value: "https://aausmartlab.com/Assets/Resource/B&R/ACOPOS6D/001"
          Other_Resource_Connection_Point_Id:
            value: "Drill_Station_Connection_Point_1"
          Position:
            X_Value:
              value: 480
            Y_Value:
              value: 120
      - Resource_Connection_2:
          Own_Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_9"
          Connection_Resource_Id:
            value: "https://aausmartlab.com/Assets/Resource/MADE/Bottom_Cover_Storage/001"
          Other_Resource_Connection_Point_Id:
            value: "Bottom_Cover_Storage_Connection_Point_1"
          Position:
            X_Value:
              value: 120
            Y_Value:
              value: 120

  Skills:
    Agents:
      - Shuttle_1:
          Capabilities:
            - Transport:
                Estimated_Duration:
                  value: 5
                Parameters:
                  Speed:
                    min: 0
                    max: 1
                  Acceleration:
                    min: 0
                    max: 5
                  Hover_Height:
                    min: 1
                    max: 3
                Supported_Connection_Points:
                  ACOPOS6D_Connection_Point_1:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_1"
                  ACOPOS6D_Connection_Point_2:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_2"
                  ACOPOS6D_Connection_Point_3:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_3"
                  ACOPOS6D_Connection_Point_4:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_4"
                  ACOPOS6D_Connection_Point_5:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_5"
                  ACOPOS6D_Connection_Point_6:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_6"
                  ACOPOS6D_Connection_Point_7:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_7"
                  ACOPOS6D_Connection_Point_8:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_8"
                  ACOPOS6D_Connection_Point_9:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_9"
                Supported_Components:
                  Bottom_Cover:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Bottom_Cover"
                  Housing_With_PCB:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Housing_With_PCB"
                  PCB_With_Fuse:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/PCB_With_Fuse"
                  Telefon_Pro_Max:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Telefon_Pro_Max"
      - Shuttle_2:
          Capabilities:
            - Transport:
                Estimated_Duration:
                  value: 5
                Parameters:
                  Speed:
                    min: 0
                    max: 1
                  Acceleration:
                    min: 0
                    max: 5
                  Hover_Height:
                    min: 1
                    max: 3
                Supported_Connection_Points:
                  ACOPOS6D_Connection_Point_1:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_1"
                  ACOPOS6D_Connection_Point_2:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_2"
                  ACOPOS6D_Connection_Point_3:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_3"
                  ACOPOS6D_Connection_Point_4:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_4"
                  ACOPOS6D_Connection_Point_5:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_5"
                  ACOPOS6D_Connection_Point_6:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_6"
                  ACOPOS6D_Connection_Point_7:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_7"
                  ACOPOS6D_Connection_Point_8:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_8"
                  ACOPOS6D_Connection_Point_9:
                    Connection_Point_Id:
                      value: "ACOPOS6D_Connection_Point_9"
                Supported_Components:
                  Bottom_Cover:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Bottom_Cover"
                  Housing_With_PCB:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Housing_With_PCB"
                  PCB_With_Fuse:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/PCB_With_Fuse"
                  Telefon_Pro_Max:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Telefon_Pro_Max"
