shell:
  id:
    value: "https://aausmartlab.com/Assets/Resource/MADE/Drill_Station/1e1d4a58-e403-4d5e-81fa-19c544835561"
  idShort:
    value: "Drilling_Station"

submodels:
  Item_Capacity:
    Internal_Part_Storages:
      - Internal_Part_Storage_1:
          Storage_Size:
            value: 1
          Storing_Method:
            value: "First_In_First_Out"
          Storage_Type:
            value: "Input_Output"
          Part_Types:
            - Part_Type_1:
                Part_Type_Id:
                  value: "https://aausmartlab.com/Assets/Product/Component/AAU/Bottom_Cover"
                Quantity:
                  value: 0

  Communication:
    Communication_Methods:
      - UNS_Communication:
          Broker_Address:
            # value: "192.168.38.200"
            value: "100.117.139.24"
          Protocol:
            value: "MQTT"
          Port:
            value: 1883
          Base_Topic:
            value: "AAU/FIB14/SmartLab/PL1/Stations"
          QoS:
            value: 2

  Location:
    General_Information:
      Building:
        value: FIB_14
      Production_Line:
        value: "Production_Line_1"

    Connection_Points:
      - Connection_Point_1:
          Connection_Point_Id:
            value: "Drill_Station_Connection_Point_1"
          Connection_Type:
            value: "In-Outfeed"

    Resource_Connections:
      - Resource_Connection_1:
          Own_Connection_Point_Id:
            value: "Drill_Station_Connection_Point_1"
          Connection_Resource_Id:
            value: "https://aausmartlab.com/Assets/Resource/B&R/ACOPOS6D/001"
          Other_Resource_Connection_Point_Id:
            value: "ACOPOS6D_Connection_Point_7"
          Position:
            X_Value:
              value: 480
            Y_Value:
              value: 120

  Skills:
    Agents:
      - KUKA_Manipulator:
          Capabilities:
            - Drilling:
                Estimated_Duration:
                  value: 5
                Parameters:
                  Drill_Depth:
                    min: 1
                    max: 20
                  Rotational_Speed:
                    min: 1500
                    max: 2000
                  Feed:
                    min: 100
                    max: 200
                  Drill_Size:
                    value: 5
                Supported_Connection_Points:
                  Drill_Station_Connection_Point_1:
                    Connection_Point_Id:
                      value: "Drill_Station_Connection_Point_1"
                Supported_Components:
                  Bottom_Cover:
                    Component_Type:
                      value: "https://aausmartlab.com/Assets/Product/Component/AAU/Bottom_Cover"
